<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \PayEx\Payments\Block\Form\MobilePay
 */
$code = $block->escapeHtml($block->getMethodCode());
?>
<fieldset class="fieldset payment items mobilepay <?php /* @noEscape */ echo $code; ?>"
          id="payment_form_<?php /* @noEscape */ echo $code; ?>" style="display: none;">
    <div style="float:left">
        <img src="<?php echo $block->getViewFileUrl('images/mobilepay_online.png'); ?>" alt="MobilePay Online" /><br />
    </div>
    <div style="float:left">
        <?php echo __('You will be redirected to <a target="_blank" href="http://www.payex.com">PayEx</a> website when you place an order.'); ?>
    </div>
    <?php //echo $block->getChildHtml() ?>
</fieldset>
