<?php
// @codingStandardsIgnoreFile
/**
 * @var $block \PayEx\Payments\Block\Info\Evc
 */
?>
<?php echo $block->escapeHtml($block->getMethod()->getTitle()) ?>
{{pdf_row_separator}}
<?php $trans_id = $block->getInfo()->getLastTransId(); ?>
<?php if (!empty($trans_id)): ?>
    <?php $_specificInfo = $block->getSpecificInformation(); ?>
    <?php if (count($_specificInfo) > 0): ?>
        <?php foreach($_specificInfo as $_label => $_value): ?>
            <?php
            if ($_label === 'PayEx Transaction Status') {
                $_value = $block->getTransactionStatusLabel($_value);
            }
            ?>
            <?php echo __($block->escapeHtml($_label)) . ': ' . $block->escapeHtml($_value); ?>
            {{pdf_row_separator}}
        <?php endforeach; ?>
    <?php endif; ?>
<?php endif; ?>
